export const officialSlogan = 'Hamro Byapar — व्यापार बुझौं, व्यवसाय बढाऔं';

const en = {
  dashboard: 'Dashboard', sales: 'Sales', inventory: 'Inventory', analytics: 'Analytics', ai: 'Hamro AI', settings: 'Settings', more: 'More',
  greeting: 'Good afternoon', overview: 'Here is how your shop is doing today.', todaySales: "Today's sales", transactions: 'Transactions', estimatedProfit: 'Estimated profit', lowStock: 'Low stock', products: 'products',
  salesTrend: 'Sales trend', revenue: 'Revenue', orders: 'Orders', profit: 'Profit', today: 'Today', sevenDays: '7 days', thirtyDays: '30 days', whatHappened: 'What happened?',
  bestSellers: 'Best sellers', slowMovers: 'Slow movers', unitsSold: 'units sold', seeInventory: 'See inventory', recentSales: 'Recent sales', seeAll: 'See all',
  addSale: 'Add sale', newSale: 'Record a sale', product: 'Product', quantity: 'Quantity', sellingPrice: 'Selling price', discount: 'Discount (optional)', total: 'Total', saveSale: 'Confirm sale', cancel: 'Cancel',
  quickSale: 'Quick sale', quickSaleHelp: 'Tap a product, choose quantity, and confirm.', selected: 'Selected', saleHistory: 'Sales history', yesterday: 'Yesterday', amount: 'Amount', time: 'Time', noSales: 'No sales recorded yet.', noSalesHelp: 'Add your first sale to start seeing business insights.',
  stock: 'Stock', price: 'Price', status: 'Status', healthy: 'Healthy', outOfStock: 'Out of stock', slowMoving: 'Slow moving', addProduct: 'Add product', newProduct: 'Add a product', productName: 'Product name', nepaliName: 'Nepali name', category: 'Category', purchasePrice: 'Purchase price', currentStock: 'Current stock', threshold: 'Low-stock threshold', saveProduct: 'Save product', updateStock: 'Update stock', stockUpdated: 'Stock and alert threshold updated.',
  inventoryAlerts: 'Inventory alerts', action: 'Suggested action', restock: 'Restock soon', watchDemand: 'Check demand before restocking', keepItUp: 'Keep enough stock available',
  aiSubtitle: 'Your simple business analyst', askAi: 'What would you like to know?', quickQuestions: 'Quick questions', aiSays: 'Hamro AI says', insight: 'Insight', why: 'Why?',
  qToday: 'What happened today?', qBest: 'What is selling best?', qSlow: 'What is not selling?', qRestock: 'Which products need restocking?', qCompare: 'How are sales vs last week?', qWatch: 'What should I watch?', localInsight: 'Works offline using your shop data',
  shopProfile: 'Shop profile', shopName: 'Shop name', ownerName: 'Owner name', shopType: 'Shop type', location: 'Location', currency: 'Currency', saveChanges: 'Save changes', demoShop: 'Demo shop', demoHelp: 'Reload realistic shop data for a polished demonstration.', loadDemo: 'Load demo shop', dataOnDevice: 'Your data stays safely on this device.',
  online: 'Online', offline: 'Offline — your data is saved on this device', language: 'Language', english: 'English', nepali: 'नेपाली', presentationMode: 'Presentation mode', presentationHelp: 'Larger type, charts, and spacing for projectors and screen sharing.', presentationEnabled: 'Presentation mode enabled.', presentationDisabled: 'Presentation mode disabled.', saleAdded: 'Sale added. Dashboard and stock updated.', productAdded: 'Product added to inventory.', saved: 'Changes saved on this device.', demoLoaded: 'Demo shop loaded and ready.', languageChanged: 'Language changed.',
  units: 'units', inStock: 'in stock', tapToSell: 'Tap to sell', close: 'Close', alerts: 'Alerts', notifications: 'Notifications', markAllRead: 'Mark all read', noNotifications: 'No stock alerts yet', noNotificationsHelp: 'New low-stock and out-of-stock alerts will appear here.', outOfStockNotification: '{product} is out of stock.', lowStockNotification: '{product} has only {stock} units remaining.', emailSent: 'Email sent', emailPending: 'Email pending', emailFailed: 'Email not sent', home: 'Home', itemsNeedAttention: 'items need attention', allCaughtUp: 'All stock levels look good.', topProductsHelp: 'Your most popular products this month',
  hamroVoice: 'Hamro Voice', voiceTagline: 'Speak naturally. We will handle the numbers.', voiceSale: 'Voice sale', speakSale: 'Speak a sale', voiceIntro: 'Tell us what you bought, what you sold it for, and the quantity. You will always review it before saving.', startSpeaking: 'Start speaking', typeInstead: 'or type what you would say', transcriptPlaceholder: 'Example: 10 packet noodles 20 ma kine, 25 ma beche.', understand: 'Understand my sale', trySaying: 'Try saying…', voiceNeedTranscript: 'Say or type a sale first.',
  startingMicrophone: 'Starting microphone…', startingMicrophoneHelp: 'Allow microphone access if your browser asks, then speak naturally about your sale.', voiceUnsupported: "Voice input isn't supported by this browser.", voiceUnsupportedHelp: 'For the best voice experience, open Hamro Byapar in Google Chrome.', voicePermissionDenied: 'Microphone permission is required.', voicePermissionTimeout: 'Microphone permission is still waiting.', voicePermissionHelp: 'Please allow microphone access in your browser settings and try again.', voiceNoSpeech: "I didn't hear anything. Please try again.", voiceMicrophoneMissing: 'No microphone was found on this device.', voiceMicrophoneBusy: 'The microphone is busy or could not be started.', voiceNetworkError: 'The browser speech service could not connect.', voiceNetworkHelp: 'Your business data still works offline. Reconnect for browser voice recognition or enter the sale manually.', voiceCancelled: 'Voice recognition was cancelled.', voiceLanguageUnsupported: 'The browser could not recognize this language.', voiceLanguageHelp: 'Hamro Voice tried the Nepali and English recognition settings. You can retry or enter the sentence manually.', voiceRecognitionFailed: 'Voice recognition could not start. Please try again.', voiceParserFailed: "I heard you, but couldn't understand the sale details.", tryAgain: 'Try again', enterManually: 'Enter manually',
  listening: 'Listening…', listeningHelp: 'Speak naturally in English, Nepali, or Romanized Nepali.', listeningPlaceholder: 'Your words will appear here…', stopListening: 'Stop listening', understandingSale: 'Understanding your sale…', hamroVoiceSays: 'Hamro Voice says', askAnother: 'Ask another', hamroVoiceUnderstood: 'Hamro Voice understood', confidence: 'confidence', missingInfo: 'I need a little more information', missingPurchase: 'What was the purchase price?', missingSelling: 'What was the selling price?', missingProduct: 'Which product was this?', matchedInventory: 'Matched to inventory', newProductDetected: 'New product detected', newProductHelp: "This product isn't currently in your inventory. Choose how to continue.", continueWithoutInventory: 'Continue without inventory', defaultQuantity: 'Defaulted to 1', boughtAt: 'Bought at', soldAt: 'Sold at', cost: 'Cost', profitPerUnit: 'Profit per unit', margin: 'Margin', edit: 'Edit', doneEditing: 'Done editing', saveVoiceSale: 'Save voice sale', saleSaved: 'Sale saved', voiceSavedInsight: '{product} generated {profit} profit from this sale.', undo: 'Undo', done: 'Done', voice: 'Voice', unitsSoldToday: 'units sold today', saleUndone: 'The voice sale was undone.',
};

const ne = {
  dashboard: 'ड्यासबोर्ड', sales: 'बिक्री', inventory: 'मौज्दात', analytics: 'विश्लेषण', ai: 'हाम्रो AI', settings: 'सेटिङ', more: 'थप',
  greeting: 'शुभ दिउँसो', overview: 'आज तपाईंको पसलको अवस्था यस्तो छ।', todaySales: 'आजको बिक्री', transactions: 'कारोबार', estimatedProfit: 'अनुमानित नाफा', lowStock: 'कम मौज्दात', products: 'सामान',
  salesTrend: 'बिक्रीको अवस्था', revenue: 'बिक्री रकम', orders: 'अर्डर', profit: 'नाफा', today: 'आज', sevenDays: '७ दिन', thirtyDays: '३० दिन', whatHappened: 'के भयो?',
  bestSellers: 'धेरै बिक्री भएका', slowMovers: 'कम बिक्री भएका', unitsSold: 'वटा बिक्री', seeInventory: 'मौज्दात हेर्नुहोस्', recentSales: 'हालैको बिक्री', seeAll: 'सबै हेर्नुहोस्',
  addSale: 'बिक्री थप्नुहोस्', newSale: 'बिक्री रेकर्ड गर्नुहोस्', product: 'सामान', quantity: 'परिमाण', sellingPrice: 'बिक्री मूल्य', discount: 'छुट (वैकल्पिक)', total: 'जम्मा', saveSale: 'बिक्री पक्का गर्नुहोस्', cancel: 'रद्द गर्नुहोस्',
  quickSale: 'छिटो बिक्री', quickSaleHelp: 'सामान छान्नुहोस्, परिमाण रोज्नुहोस् र पक्का गर्नुहोस्।', selected: 'छानिएको', saleHistory: 'बिक्री इतिहास', yesterday: 'हिजो', amount: 'रकम', time: 'समय', noSales: 'अहिलेसम्म कुनै बिक्री रेकर्ड गरिएको छैन।', noSalesHelp: 'व्यापारको जानकारी हेर्न आफ्नो पहिलो बिक्री थप्नुहोस्।',
  stock: 'मौज्दात', price: 'मूल्य', status: 'अवस्था', healthy: 'पर्याप्त', outOfStock: 'सकिएको', slowMoving: 'कम बिक्री', addProduct: 'सामान थप्नुहोस्', newProduct: 'नयाँ सामान थप्नुहोस्', productName: 'सामानको नाम', nepaliName: 'नेपाली नाम', category: 'वर्ग', purchasePrice: 'खरिद मूल्य', currentStock: 'हालको मौज्दात', threshold: 'कम मौज्दात सीमा', saveProduct: 'सामान सुरक्षित गर्नुहोस्', updateStock: 'मौज्दात अपडेट', stockUpdated: 'मौज्दात र सूचना सीमा अपडेट भयो।',
  inventoryAlerts: 'मौज्दात सूचना', action: 'सुझाव', restock: 'चाँडै पुनः स्टक गर्नुहोस्', watchDemand: 'पुनः स्टक गर्नुअघि माग जाँच गर्नुहोस्', keepItUp: 'पर्याप्त मौज्दात राख्नुहोस्',
  aiSubtitle: 'तपाईंको सरल व्यापार विश्लेषक', askAi: 'तपाईं के जान्न चाहनुहुन्छ?', quickQuestions: 'छिटो प्रश्न', aiSays: 'हाम्रो AI को सुझाव', insight: 'जानकारी', why: 'किन?',
  qToday: 'आज के भयो?', qBest: 'सबैभन्दा धेरै के बिक्दैछ?', qSlow: 'के बिकिरहेको छैन?', qRestock: 'कुन सामान पुनः स्टक गर्ने?', qCompare: 'गत हप्ताभन्दा बिक्री कस्तो छ?', qWatch: 'मैले केमा ध्यान दिने?', localInsight: 'तपाईंको पसलको तथ्याङ्क प्रयोग गरी अफलाइन पनि चल्छ',
  shopProfile: 'पसल विवरण', shopName: 'पसलको नाम', ownerName: 'सञ्चालकको नाम', shopType: 'पसलको प्रकार', location: 'ठेगाना', currency: 'मुद्रा', saveChanges: 'परिवर्तन सुरक्षित गर्नुहोस्', demoShop: 'डेमो पसल', demoHelp: 'प्रदर्शनका लागि वास्तविक जस्तो पसलको तथ्याङ्क फेरि भर्नुहोस्।', loadDemo: 'डेमो पसल लोड गर्नुहोस्', dataOnDevice: 'तपाईंको तथ्याङ्क यसै उपकरणमा सुरक्षित रहन्छ।',
  online: 'अनलाइन', offline: 'अफलाइन — तपाईंको तथ्याङ्क यस उपकरणमा सुरक्षित छ', language: 'भाषा', english: 'English', nepali: 'नेपाली', presentationMode: 'प्रस्तुति मोड', presentationHelp: 'प्रोजेक्टर र स्क्रिन सेयरका लागि ठूला अक्षर, चार्ट र फराकिलो ठाउँ।', presentationEnabled: 'प्रस्तुति मोड सुरु भयो।', presentationDisabled: 'प्रस्तुति मोड बन्द भयो।', saleAdded: 'बिक्री थपियो। ड्यासबोर्ड र मौज्दात अपडेट भयो।', productAdded: 'सामान मौज्दातमा थपियो।', saved: 'परिवर्तन यस उपकरणमा सुरक्षित भयो।', demoLoaded: 'डेमो पसल तयार भयो।', languageChanged: 'भाषा परिवर्तन भयो।',
  units: 'वटा', inStock: 'मौज्दातमा', tapToSell: 'बिक्री गर्न थिच्नुहोस्', close: 'बन्द गर्नुहोस्', alerts: 'सूचना', notifications: 'सूचनाहरू', markAllRead: 'सबै पढिएको चिन्ह लगाउनुहोस्', noNotifications: 'अहिलेसम्म मौज्दात सूचना छैन', noNotificationsHelp: 'नयाँ कम मौज्दात र सकिएका सामानका सूचना यहाँ देखिन्छन्।', outOfStockNotification: '{product} को मौज्दात सकिएको छ।', lowStockNotification: '{product} केवल {stock} वटा बाँकी छ।', emailSent: 'इमेल पठाइयो', emailPending: 'इमेल पठाउँदै', emailFailed: 'इमेल पठाउन सकिएन', home: 'गृहपृष्ठ', itemsNeedAttention: 'सामानमा ध्यान दिनुहोस्', allCaughtUp: 'सबै सामानको मौज्दात ठीक छ।', topProductsHelp: 'यो महिनाका लोकप्रिय सामान',
  hamroVoice: 'हाम्रो भ्वाइस', voiceTagline: 'बोल्नुहोस्, हिसाब हामी गर्छौं।', voiceSale: 'आवाजबाट बिक्री', speakSale: 'बिक्री बोल्नुहोस्', voiceIntro: 'कति सामान, कति रुपैयाँमा किन्नुभयो र कति रुपैयाँमा बेच्नुभयो भन्नुहोस्। सुरक्षित गर्नुअघि सधैं जाँच गर्न पाउनुहुन्छ।', startSpeaking: 'बोल्न सुरु गर्नुहोस्', typeInstead: 'वा आफूले बोल्ने कुरा लेख्नुहोस्', transcriptPlaceholder: 'उदाहरण: १० प्याकेट चाउचाउ २० मा किनेँ, २५ मा बेचेँ।', understand: 'मेरो बिक्री बुझ्नुहोस्', trySaying: 'यसरी भन्नुहोस्…', voiceNeedTranscript: 'पहिले बिक्री बोल्नुहोस् वा लेख्नुहोस्।',
  startingMicrophone: 'माइक्रोफोन सुरु हुँदैछ…', startingMicrophoneHelp: 'ब्राउजरले सोधेमा माइक्रोफोन अनुमति दिनुहोस्, त्यसपछि आफ्नो बिक्रीबारे स्वाभाविक रूपमा बोल्नुहोस्।', voiceUnsupported: 'यो ब्राउजरमा आवाज इनपुट समर्थित छैन।', voiceUnsupportedHelp: 'उत्तम आवाज अनुभवका लागि Hamro Byapar लाई Google Chrome मा खोल्नुहोस्।', voicePermissionDenied: 'माइक्रोफोन अनुमति आवश्यक छ।', voicePermissionTimeout: 'माइक्रोफोन अनुमति अझै पर्खिरहेको छ।', voicePermissionHelp: 'ब्राउजर सेटिङमा माइक्रोफोन पहुँच अनुमति दिएर फेरि प्रयास गर्नुहोस्।', voiceNoSpeech: 'मैले केही सुनिनँ। कृपया फेरि प्रयास गर्नुहोस्।', voiceMicrophoneMissing: 'यो उपकरणमा माइक्रोफोन भेटिएन।', voiceMicrophoneBusy: 'माइक्रोफोन व्यस्त छ वा सुरु हुन सकेन।', voiceNetworkError: 'ब्राउजरको आवाज सेवासँग जडान हुन सकेन।', voiceNetworkHelp: 'तपाईंको व्यापारको तथ्याङ्क अफलाइन पनि चल्छ। ब्राउजर आवाजका लागि इन्टरनेट जोड्नुहोस् वा बिक्री आफैं लेख्नुहोस्।', voiceCancelled: 'आवाज पहिचान रद्द भयो।', voiceLanguageUnsupported: 'ब्राउजरले यो भाषा पहिचान गर्न सकेन।', voiceLanguageHelp: 'हाम्रो भ्वाइसले नेपाली र English दुवै सेटिङ प्रयास गर्‍यो। फेरि प्रयास गर्नुहोस् वा वाक्य लेख्नुहोस्।', voiceRecognitionFailed: 'आवाज पहिचान सुरु हुन सकेन। फेरि प्रयास गर्नुहोस्।', voiceParserFailed: 'मैले सुनेँ, तर बिक्रीको विवरण बुझ्न सकिनँ।', tryAgain: 'फेरि प्रयास गर्नुहोस्', enterManually: 'आफैं लेख्नुहोस्',
  listening: 'सुन्दैछु…', listeningHelp: 'नेपाली, English वा Romanized Nepali मा स्वाभाविक रूपमा बोल्नुहोस्।', listeningPlaceholder: 'तपाईंको बोली यहाँ देखिन्छ…', stopListening: 'सुन्न रोक्नुहोस्', understandingSale: 'तपाईंको बिक्री बुझ्दैछु…', hamroVoiceSays: 'हाम्रो भ्वाइसको जवाफ', askAnother: 'अर्को सोध्नुहोस्', hamroVoiceUnderstood: 'हाम्रो भ्वाइसले बुझेको', confidence: 'विश्वास', missingInfo: 'मलाई अलि थप जानकारी चाहियो', missingPurchase: 'खरिद मूल्य कति थियो?', missingSelling: 'बिक्री मूल्य कति थियो?', missingProduct: 'यो कुन सामान थियो?', matchedInventory: 'मौज्दातसँग मिल्यो', newProductDetected: 'नयाँ सामान भेटियो', newProductHelp: 'यो सामान अहिले मौज्दातमा छैन। कसरी अगाडि बढ्ने छान्नुहोस्।', continueWithoutInventory: 'मौज्दातबिना जारी राख्नुहोस्', defaultQuantity: '१ मानिएको', boughtAt: 'खरिद मूल्य', soldAt: 'बिक्री मूल्य', cost: 'लागत', profitPerUnit: 'प्रति वटा नाफा', margin: 'नाफा प्रतिशत', edit: 'सच्याउनुहोस्', doneEditing: 'सच्याइयो', saveVoiceSale: 'आवाज बिक्री सुरक्षित गर्नुहोस्', saleSaved: 'बिक्री सुरक्षित भयो', voiceSavedInsight: '{product} बाट यो बिक्रीमा {profit} नाफा भयो।', undo: 'फिर्ता गर्नुहोस्', done: 'सकियो', voice: 'आवाज', unitsSoldToday: 'वटा आज बिक्री', saleUndone: 'आवाजबाट थपिएको बिक्री फिर्ता भयो।',
};

export const translations = { en, ne };
export const translate = (lang, key) => translations[lang]?.[key] || translations.en[key] || key;
